/*
 * This file is generated by jOOQ.
 */
package userprofile.persistence.jooq;


import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;

import userprofile.persistence.jooq.tables.Listener;
import userprofile.persistence.jooq.tables.ListenerUser;
import userprofile.persistence.jooq.tables.Token;
import userprofile.persistence.jooq.tables.UserAudit;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class App extends SchemaImpl {

    private static final long serialVersionUID = -974788918;

    /**
     * The reference instance of <code>APP</code>
     */
    public static final App APP = new App();

    /**
     * The table <code>APP.LISTENER</code>.
     */
    public final Listener LISTENER = Listener.LISTENER;

    /**
     * The table <code>APP.LISTENER_USER</code>.
     */
    public final ListenerUser LISTENER_USER = ListenerUser.LISTENER_USER;

    /**
     * The table <code>APP.TOKEN</code>.
     */
    public final Token TOKEN = Token.TOKEN;

    /**
     * The table <code>APP.USER_AUDIT</code>.
     */
    public final UserAudit USER_AUDIT = UserAudit.USER_AUDIT;

    /**
     * No further instances allowed
     */
    private App() {
        super("APP", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.<Table<?>>asList(
            Listener.LISTENER,
            ListenerUser.LISTENER_USER,
            Token.TOKEN,
            UserAudit.USER_AUDIT);
    }
}
