/*
 * This file is generated by jOOQ.
 */
package userprofile.persistence.jooq;


import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.Internal;

import userprofile.persistence.jooq.tables.Listener;
import userprofile.persistence.jooq.tables.ListenerUser;
import userprofile.persistence.jooq.tables.Token;
import userprofile.persistence.jooq.tables.UserAudit;
import userprofile.persistence.jooq.tables.records.ListenerRecord;
import userprofile.persistence.jooq.tables.records.ListenerUserRecord;
import userprofile.persistence.jooq.tables.records.TokenRecord;
import userprofile.persistence.jooq.tables.records.UserAuditRecord;


/**
 * A class modelling foreign key relationships and constraints of tables of 
 * the <code>APP</code> schema.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------

    public static final Identity<ListenerRecord, Integer> IDENTITY_LISTENER = Identities0.IDENTITY_LISTENER;
    public static final Identity<ListenerUserRecord, Integer> IDENTITY_LISTENER_USER = Identities0.IDENTITY_LISTENER_USER;

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<ListenerRecord> SQL0000000032_D3E50CE9_0172_B50B_E31B_FFFFC60AC551 = UniqueKeys0.SQL0000000032_D3E50CE9_0172_B50B_E31B_FFFFC60AC551;
    public static final UniqueKey<ListenerUserRecord> SQL0000000034_F8FA4CF2_0172_B50B_E31B_FFFFC60AC551 = UniqueKeys0.SQL0000000034_F8FA4CF2_0172_B50B_E31B_FFFFC60AC551;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

    public static final ForeignKey<ListenerUserRecord, ListenerRecord> SQL0000000033_6DBE0CF1_0172_B50B_E31B_FFFFC60AC551 = ForeignKeys0.SQL0000000033_6DBE0CF1_0172_B50B_E31B_FFFFC60AC551;
    public static final ForeignKey<TokenRecord, ListenerUserRecord> SQL0000000035_2E23CCFB_0172_B50B_E31B_FFFFC60AC551 = ForeignKeys0.SQL0000000035_2E23CCFB_0172_B50B_E31B_FFFFC60AC551;
    public static final ForeignKey<UserAuditRecord, ListenerUserRecord> SQL0000000036_A1A00D01_0172_B50B_E31B_FFFFC60AC551 = ForeignKeys0.SQL0000000036_A1A00D01_0172_B50B_E31B_FFFFC60AC551;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Identities0 {
        public static Identity<ListenerRecord, Integer> IDENTITY_LISTENER = Internal.createIdentity(Listener.LISTENER, Listener.LISTENER.ID_LISTENER);
        public static Identity<ListenerUserRecord, Integer> IDENTITY_LISTENER_USER = Internal.createIdentity(ListenerUser.LISTENER_USER, ListenerUser.LISTENER_USER.ID_USER);
    }

    private static class UniqueKeys0 {
        public static final UniqueKey<ListenerRecord> SQL0000000032_D3E50CE9_0172_B50B_E31B_FFFFC60AC551 = Internal.createUniqueKey(Listener.LISTENER, "SQL0000000032-d3e50ce9-0172-b50b-e31b-ffffc60ac551", new TableField[] { Listener.LISTENER.ID_LISTENER }, true);
        public static final UniqueKey<ListenerUserRecord> SQL0000000034_F8FA4CF2_0172_B50B_E31B_FFFFC60AC551 = Internal.createUniqueKey(ListenerUser.LISTENER_USER, "SQL0000000034-f8fa4cf2-0172-b50b-e31b-ffffc60ac551", new TableField[] { ListenerUser.LISTENER_USER.ID_USER }, true);
    }

    private static class ForeignKeys0 {
        public static final ForeignKey<ListenerUserRecord, ListenerRecord> SQL0000000033_6DBE0CF1_0172_B50B_E31B_FFFFC60AC551 = Internal.createForeignKey(Keys.SQL0000000032_D3E50CE9_0172_B50B_E31B_FFFFC60AC551, ListenerUser.LISTENER_USER, "SQL0000000033-6dbe0cf1-0172-b50b-e31b-ffffc60ac551", new TableField[] { ListenerUser.LISTENER_USER.ID_LISTENER }, true);
        public static final ForeignKey<TokenRecord, ListenerUserRecord> SQL0000000035_2E23CCFB_0172_B50B_E31B_FFFFC60AC551 = Internal.createForeignKey(Keys.SQL0000000034_F8FA4CF2_0172_B50B_E31B_FFFFC60AC551, Token.TOKEN, "SQL0000000035-2e23ccfb-0172-b50b-e31b-ffffc60ac551", new TableField[] { Token.TOKEN.ID_USER }, true);
        public static final ForeignKey<UserAuditRecord, ListenerUserRecord> SQL0000000036_A1A00D01_0172_B50B_E31B_FFFFC60AC551 = Internal.createForeignKey(Keys.SQL0000000034_F8FA4CF2_0172_B50B_E31B_FFFFC60AC551, UserAudit.USER_AUDIT, "SQL0000000036-a1a00d01-0172-b50b-e31b-ffffc60ac551", new TableField[] { UserAudit.USER_AUDIT.ID_USER }, true);
    }
}
