/*
 * This file is generated by jOOQ.
 */
package userprofile.persistence.jooq.tables.records;


import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;

import userprofile.persistence.jooq.tables.ListenerUser;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ListenerUserRecord extends UpdatableRecordImpl<ListenerUserRecord> implements Record5<Integer, Integer, LocalDateTime, String, String> {

    private static final long serialVersionUID = 1480376225;

    /**
     * Setter for <code>APP.LISTENER_USER.ID_USER</code>.
     */
    public void setIdUser(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>APP.LISTENER_USER.ID_USER</code>.
     */
    public Integer getIdUser() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>APP.LISTENER_USER.ID_LISTENER</code>.
     */
    public void setIdListener(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>APP.LISTENER_USER.ID_LISTENER</code>.
     */
    public Integer getIdListener() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>APP.LISTENER_USER.CREATION_DATE</code>.
     */
    public void setCreationDate(LocalDateTime value) {
        set(2, value);
    }

    /**
     * Getter for <code>APP.LISTENER_USER.CREATION_DATE</code>.
     */
    public LocalDateTime getCreationDate() {
        return (LocalDateTime) get(2);
    }

    /**
     * Setter for <code>APP.LISTENER_USER.USERNAME</code>.
     */
    public void setUsername(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>APP.LISTENER_USER.USERNAME</code>.
     */
    public String getUsername() {
        return (String) get(3);
    }

    /**
     * Setter for <code>APP.LISTENER_USER.PASSWORD</code>.
     */
    public void setPassword(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>APP.LISTENER_USER.PASSWORD</code>.
     */
    public String getPassword() {
        return (String) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row5<Integer, Integer, LocalDateTime, String, String> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    @Override
    public Row5<Integer, Integer, LocalDateTime, String, String> valuesRow() {
        return (Row5) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return ListenerUser.LISTENER_USER.ID_USER;
    }

    @Override
    public Field<Integer> field2() {
        return ListenerUser.LISTENER_USER.ID_LISTENER;
    }

    @Override
    public Field<LocalDateTime> field3() {
        return ListenerUser.LISTENER_USER.CREATION_DATE;
    }

    @Override
    public Field<String> field4() {
        return ListenerUser.LISTENER_USER.USERNAME;
    }

    @Override
    public Field<String> field5() {
        return ListenerUser.LISTENER_USER.PASSWORD;
    }

    @Override
    public Integer component1() {
        return getIdUser();
    }

    @Override
    public Integer component2() {
        return getIdListener();
    }

    @Override
    public LocalDateTime component3() {
        return getCreationDate();
    }

    @Override
    public String component4() {
        return getUsername();
    }

    @Override
    public String component5() {
        return getPassword();
    }

    @Override
    public Integer value1() {
        return getIdUser();
    }

    @Override
    public Integer value2() {
        return getIdListener();
    }

    @Override
    public LocalDateTime value3() {
        return getCreationDate();
    }

    @Override
    public String value4() {
        return getUsername();
    }

    @Override
    public String value5() {
        return getPassword();
    }

    @Override
    public ListenerUserRecord value1(Integer value) {
        setIdUser(value);
        return this;
    }

    @Override
    public ListenerUserRecord value2(Integer value) {
        setIdListener(value);
        return this;
    }

    @Override
    public ListenerUserRecord value3(LocalDateTime value) {
        setCreationDate(value);
        return this;
    }

    @Override
    public ListenerUserRecord value4(String value) {
        setUsername(value);
        return this;
    }

    @Override
    public ListenerUserRecord value5(String value) {
        setPassword(value);
        return this;
    }

    @Override
    public ListenerUserRecord values(Integer value1, Integer value2, LocalDateTime value3, String value4, String value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ListenerUserRecord
     */
    public ListenerUserRecord() {
        super(ListenerUser.LISTENER_USER);
    }

    /**
     * Create a detached, initialised ListenerUserRecord
     */
    public ListenerUserRecord(Integer idUser, Integer idListener, LocalDateTime creationDate, String username, String password) {
        super(ListenerUser.LISTENER_USER);

        set(0, idUser);
        set(1, idListener);
        set(2, creationDate);
        set(3, username);
        set(4, password);
    }
}
