/*
 * This file is generated by jOOQ.
 */
package userprofile.persistence.jooq.tables.records;


import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;

import userprofile.persistence.jooq.tables.Listener;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ListenerRecord extends UpdatableRecordImpl<ListenerRecord> implements Record6<Integer, String, String, String, String, String> {

    private static final long serialVersionUID = -2002597760;

    /**
     * Setter for <code>APP.LISTENER.ID_LISTENER</code>.
     */
    public void setIdListener(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>APP.LISTENER.ID_LISTENER</code>.
     */
    public Integer getIdListener() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>APP.LISTENER.NAME</code>.
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>APP.LISTENER.NAME</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>APP.LISTENER.SURNAME</code>.
     */
    public void setSurname(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>APP.LISTENER.SURNAME</code>.
     */
    public String getSurname() {
        return (String) get(2);
    }

    /**
     * Setter for <code>APP.LISTENER.PHONE</code>.
     */
    public void setPhone(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>APP.LISTENER.PHONE</code>.
     */
    public String getPhone() {
        return (String) get(3);
    }

    /**
     * Setter for <code>APP.LISTENER.EMAIL</code>.
     */
    public void setEmail(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>APP.LISTENER.EMAIL</code>.
     */
    public String getEmail() {
        return (String) get(4);
    }

    /**
     * Setter for <code>APP.LISTENER.PERSON_ID</code>.
     */
    public void setPersonId(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>APP.LISTENER.PERSON_ID</code>.
     */
    public String getPersonId() {
        return (String) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row6<Integer, String, String, String, String, String> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    @Override
    public Row6<Integer, String, String, String, String, String> valuesRow() {
        return (Row6) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return Listener.LISTENER.ID_LISTENER;
    }

    @Override
    public Field<String> field2() {
        return Listener.LISTENER.NAME;
    }

    @Override
    public Field<String> field3() {
        return Listener.LISTENER.SURNAME;
    }

    @Override
    public Field<String> field4() {
        return Listener.LISTENER.PHONE;
    }

    @Override
    public Field<String> field5() {
        return Listener.LISTENER.EMAIL;
    }

    @Override
    public Field<String> field6() {
        return Listener.LISTENER.PERSON_ID;
    }

    @Override
    public Integer component1() {
        return getIdListener();
    }

    @Override
    public String component2() {
        return getName();
    }

    @Override
    public String component3() {
        return getSurname();
    }

    @Override
    public String component4() {
        return getPhone();
    }

    @Override
    public String component5() {
        return getEmail();
    }

    @Override
    public String component6() {
        return getPersonId();
    }

    @Override
    public Integer value1() {
        return getIdListener();
    }

    @Override
    public String value2() {
        return getName();
    }

    @Override
    public String value3() {
        return getSurname();
    }

    @Override
    public String value4() {
        return getPhone();
    }

    @Override
    public String value5() {
        return getEmail();
    }

    @Override
    public String value6() {
        return getPersonId();
    }

    @Override
    public ListenerRecord value1(Integer value) {
        setIdListener(value);
        return this;
    }

    @Override
    public ListenerRecord value2(String value) {
        setName(value);
        return this;
    }

    @Override
    public ListenerRecord value3(String value) {
        setSurname(value);
        return this;
    }

    @Override
    public ListenerRecord value4(String value) {
        setPhone(value);
        return this;
    }

    @Override
    public ListenerRecord value5(String value) {
        setEmail(value);
        return this;
    }

    @Override
    public ListenerRecord value6(String value) {
        setPersonId(value);
        return this;
    }

    @Override
    public ListenerRecord values(Integer value1, String value2, String value3, String value4, String value5, String value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ListenerRecord
     */
    public ListenerRecord() {
        super(Listener.LISTENER);
    }

    /**
     * Create a detached, initialised ListenerRecord
     */
    public ListenerRecord(Integer idListener, String name, String surname, String phone, String email, String personId) {
        super(Listener.LISTENER);

        set(0, idListener);
        set(1, name);
        set(2, surname);
        set(3, phone);
        set(4, email);
        set(5, personId);
    }
}
